"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.services = void 0;
const users_1 = require("./users/users");
const lessons_1 = require("./lessons/lessons");
const attendance_1 = require("./attendance/attendance");
const students_1 = require("./students/students");
const schedule_1 = require("./schedule/schedule");
const subject_1 = require("./subject/subject");
const classroom_1 = require("./classroom/classroom");
const teacher_schedule_1 = require("./teacher-schedule/teacher-schedule");
const teacher_lessons_1 = require("./teacher-lessons/teacher-lessons");
const class_attendance_1 = require("./class-attendance/class-attendance");
const class_report_1 = require("./class-report/class-report");
const student_card_1 = require("./student-card/student-card");
const semester_week_1 = require("./semester-week/semester-week");
const record_attendance_1 = require("./record-attendance/record-attendance");
const login_1 = require("./login/login");
const backup_1 = require("./backup/backup");
const analytics_1 = require("./analytics/analytics");
const services = (app) => {
    app.configure(users_1.users);
    app.configure(login_1.login);
    app.configure(lessons_1.lessons);
    app.configure(attendance_1.attendance);
    app.configure(students_1.students);
    app.configure(schedule_1.schedule);
    app.configure(subject_1.subject);
    app.configure(classroom_1.classroom);
    app.configure(teacher_schedule_1.teacherSchedule);
    app.configure(teacher_lessons_1.teacherLessons);
    app.configure(class_attendance_1.classAttendance);
    app.configure(class_report_1.classReport);
    app.configure(student_card_1.studentCard);
    app.configure(semester_week_1.semesterWeek);
    app.configure(record_attendance_1.recordAttendance);
    app.configure(backup_1.backup);
    app.configure(analytics_1.analytics);
    // All services will be registered here
};
exports.services = services;
//# sourceMappingURL=index.js.map